In [39]:
import pandas as pd

In [2]:
s = "python"

In [3]:
list(s)

['p', 'y', 't', 'h', 'o', 'n']

In [4]:
s[:3]

'pyt'

## String formatting
Python has system for string formatting using templates. String object support format method that act on the template:

In [8]:
template = "{0:.2f} {1:s} are worth ETH{2:d}"
template.format(124.12, "BTC", 1)

'124.12 BTC are worth ETH1'

In [11]:
a = 15
b = 14.65
c = "meassure"
result = f"{a} is equal to {b} units of {c}"
print(result)

15 is equal to 14.65 units of meassure


In [1]:
import numpy as np

In [18]:
data = np.array([[1.5,-0.1, 3], [4, -3, 6.5]])
1/data

array([[  0.66666667, -10.        ,   0.33333333],
       [  0.25      ,  -0.33333333,   0.15384615]])

In [33]:
arr = np.arange(10)
arr[5:8] = 12
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [34]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [35]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [36]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
obj = pd.Series([4, 7, -5, 3])

In [41]:
obj

0    4
1    7
2   -5
3    3
dtype: int64